### ISSUE TITLE
Support for Rails 6?

### ISSUE THREAD

**Issue by mjfrey** [simukappu/activity_notification#102]
I am currently using Rails 6rc1 and trying to install.  I am getting an error:

activity_notification (~> 1.7.1) was resolved to 1.7.1, which depends on
      railties (>= 4.2.0, < 5.3)

Can I get around this issue?

**Comment by simukappu** [comment]
Hi,
Current gem dependency requires < Rails 5.3. You can pull the gem repository, modify [activity_notification.gemspec](https://github.com/simukappu/activity_notification/blob/master/activity_notification.gemspec#L23), and run the gem with Rails 6.
However, it has not been tested yet. We will follow Rails update, but we would appreciate it if you could contribute for `activity_notification` to support Rails 6.

**Comment by mjfrey** [comment]
Okay I will give it a try with Rails 6 and let you know.

**Comment by mjfrey** [comment]
Everything seems to be working.  There are a few deprivation warnings that I will post here:

**Comment by simukappu** [comment]
We've published v2.0.0 which allows use with Rails 6.
https://rubygems.org/gems/activity_notification/versions/2.0.0

Please try v2 gem and give us any feedback if it works for you!
