### ISSUE TITLE
Handle Slack::Notifier::APIError exception for multiple users

### ISSUE THREAD

**Issue by sushil-bsmarter** [simukappu/activity_notification#103]
I have added the slack as an optional targets and got slack working to send notifications to individual users. My use case is once an admin creates an event, the notification gets sent to all the users.

However, once a user slack notification does not work and the application encounters Slack::Notifier::APIError, it stops sending notification to remaining users. How can I continue to send notification to remaining users even if it fails for some? Please help.

**Comment by simukappu** [comment]
Prioritized. Error at optional target function will be rescued in the next minor version.

**Comment by simukappu** [comment]
Released as v2.1.0. Thanks!
