### ISSUE TITLE
The wiki has some confusing descrptions about the mail view file path 

### ISSUE THREAD

**Issue by zll11111** [simukappu/activity_notification#104]
In the wiki, [ Email templates section](https://github.com/simukappu/activity_notification#email-templates):
**activity_notification will look for email template in the same way as notification views. For example, if you have a notification with :key set to "notification.comment.reply" and target_type users, the gem will look for a partial in app/views/activity_notification/mailer/users/comment/_reply.html.(|erb|haml|slim|something_else).**
The truth is the view file name is just the last word of the key split by the period, not started with an underscore. The gem will look for the partial file app/views/activity_notification/mailer/users/comment/reply.html.

**Comment by simukappu** [comment]
Thank you for your feedback!
Can you create pull request to make this README clearer?

**Comment by simukappu** [comment]
Add reference to #105.

**Comment by simukappu** [comment]
Merged. Thank you for your contribution!
