### ISSUE TITLE
Dependent Destroy on Target Model

### ISSUE THREAD

**Issue by amfazlani** [simukappu/activity_notification#110]
Hi, Thank you for this gem. I had a quick question about how you would delete associated notifications when a particular model is destroyed. For example a Project model has acts_as_notifiable attached to it. But when project is deleted there are still notifications that point notifiable to that project even tho it still doesn't exist. Trying to figure out a way I can delete the associated notifications when project is deleted like 'has_many :notifications, dependent destroy' would work in other has many relationships.

**Comment by simukappu** [comment]
You can use *:dependent_notifications* option in *acts_as_notifiable* function like this:
```ruby
class Project < ActiveRecord::Base
  acts_as_notifiable :users, targets: User.all, dependent_notifications: :delete_all
end
```
See [code document](https://github.com/simukappu/activity_notification/blob/master/lib/activity_notification/roles/acts_as_notifiable.rb#L173) for more details. (Document server https://www.rubydoc.info seems to be currently unavailable)

**Comment by simukappu** [comment]
Please close this issue if your questions are resolved.

**Comment by amfazlani** [comment]
Hi, sorry for the late reply. That is what I was looking for thank you. Thank you so much.
