### ISSUE TITLE
how to return Subscriptions / Settings for Notifications in API JSON ?

### ISSUE THREAD

**Issue by farooqch11** [simukappu/activity_notification#113]
Please share code if anyone has done it with api, i need to know all keys and turn on and turn off notifications and emails for them through api.

**Comment by simukappu** [comment]
Working in progress to create api mode for *activity_notification*.

**Comment by farooqch11** [comment]
@simukappu  can i contribute ?

**Comment by simukappu** [comment]
WIP development branch is here.
https://github.com/simukappu/activity_notification/commits/development

**Comment by simukappu** [comment]
Released as v2.1.0. Thanks!
