### ISSUE TITLE
can i use for mongoid Mongodb database

### ISSUE THREAD

**Issue by FarihulR** [simukappu/activity_notification#12]
can i use it for mongoid Mongodb database

**Comment by simukappu** [comment]
Currently no, but that will be good function.
We have to implement Notification model for mongoid which does not depend on ActiveRecord ORM.

**Comment by simukappu** [comment]
ActivityNotification with Mongoid ORM for MongoDB is now supported in version 1.3.0!
There are still several problem, solving N+1 calling for example, but it works fine.
I will close this issue.
