### ISSUE TITLE
No way to customize Notification model?

### ISSUE THREAD

**Issue by victormb012** [simukappu/activity_notification#121]
Hello

I wish to be able to customize the notification model.
Try using **rails generate activity_notification:models** but the created file do not overwrite the original model. 
Is there a way to do it ?

**Comment by simukappu** [comment]
Hi,

Yes, you can use **rails generate activity_notification:models** and generate custom models:
```bash
bin/rails g activity_notification:models custom
```
Then, your custom model which overrides *ActivityNotification::Notification* will be generated.
```ruby
class Custom::Notification < ActivityNotification::Notification
  # Write custom methods or override methods here
end
```
You can use your own models with same database table used by the original models. Ensure you have configured table name in your initializer *activity_notification.rb*.
```ruby
config.notification_table_name = "notifications"
config.subscription_table_name = "subscriptions"
```

Now you can call API of *ActivityNotification::Notification* model such as *notify* method from your custom model:
```ruby
Custom::Notification.notify :users, @comment, key: "comment.reply"
```

However, the default controller or target module's API in the gem does not use this custom models.
If you need such integration with controllers or APIs, please provide more detailed feedback about your use cases.
Thanks!

**Comment by victormb012** [comment]
Perfect, thank you !!

**Comment by simukappu** [comment]
Yes, currently, target module's API in the gem such as *target.notifications*does not use the custom model. You can filter the notifications your self like this:
```ruby
Custom::Notification.where(target: target)
```
or you can override *ActivityNotification::Notification* itself:
```ruby
class ActivityNotification::Notification
  # Write custom methods or override methods here
end
```

Why do you need to customize notification model? I would appreciate it if you could give us feedback about you use cases.
Thanks!

**Comment by christopher-avila** [comment]
Ey, regarding to this issue: 

Is there any way to extend the model of Notification in terms of adding relations or custom fields, or so? 

Thanks!

**Comment by christopher-avila** [comment]
@simukappu Is there any way to keep using `acts_as_target` or `acts_as_notifiable` even with a `Custom::Notification`? I'm extending the `ActivityNotification::Notification` model to add some fields, and by using callbacks, like `before_validation` I can get some fields updated. But it doesn't work for notifications created via `tracked`. What are your thoughts about this? 

Thanks!

**Comment by christopher-avila** [comment]
Working with this approach that @simukappu commented, if you add 

```
class ActivityNotification::Notification
  # Write custom methods or override methods here
end
```

To the `config/initializers/activity_notification` where all the configuration is being placed, it works for me: adding columns and creating functions on hooks.

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.
