### ISSUE TITLE
Rails app crashes when `eager_load` is true in production

### ISSUE THREAD

**Issue by josephktcheung** [simukappu/activity_notification#124]
### Steps to reproduce

1. Create a new rails app and add `activity_notification` and `devise_token_auth` to gemfile
2. Run `bin/rails generate activity_notification:install `
3. Run `RAILS_ENV=production bundle e rails s`
4. App crashes with following error
```
lib/ruby/gems/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `block in load_missing_constant': uninitialized constant ActivityNotification::VERSION
```

### Expected behavior

It should not crash
### Actual behavior

It crashes
### System configuration
**activity_notification gem version**: 2.1.0
**Rails version**: 5.2.4.1
**ORM (ActiveRecord, Mongoid or Dynamoid)**: ActiveRecord

**Comment by simukappu** [comment]
We've merge your PR and released as v2.1.1. Thank you for your feedback and contribution!
