### ISSUE TITLE
Rails 6 - Notification with ActionCable

### ISSUE THREAD

**Issue by truongnmt** [simukappu/activity_notification#131]
Hi, first of all, what a great gem. Amazing, sincerely.

I'm trying to show notifications in real-time with ActionCable. I'm using Rails 6. Since Rails 6 introduces webpack as a default. I'm getting trouble in writing subscription to channel.

I got ActionCable to broadcast notification:
> [ActionCable] Broadcasting to activity_notification_channel_User#4: {:id=>33, :view=>" ....

I just don't know how to write subscription to channel. On seeing the [documentation ](https://github.com/simukappu/activity_notification/blob/master/docs/Functions.md#subscribing-notifications-from-channels)

```ruby
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/push.js/1.0.9/push.min.js"></script>
<script>
  App.activity_notification = App.cable.subscriptions.create(
    {
      channel: "ActivityNotification::NotificationChannel",
      target_type: "<%= @target.to_class_name %>", target_id: "<%= @target.id %>"
    },
    {
      connected: function() {
        // Connected
      },
      disconnected: function() {
        // Disconnected
      },
      rejected: function() {
        // Rejected
      },
      received: function(notification) {
        // Display notification

        // Push notificaion using Web Notification API by Push.js
        Push.create('ActivityNotification', {
          body: notification.text,
          timeout: 5000,
          onClick: function () {
            location.href = notification.notifiable_path;
            this.close();
          }
        });
      }
    }
  );
</script>
```

I think on Rails 6 we should put this in app/javascript/packs/application.js right? If so, I got error that:

> App is not defined

On a second thought, seeing embedded ruby code in js, I think we should write in `xxx.js.erb` or `...erb` file type. So I move the above code to app/vies/layout/application.html.erb

However, I got the same error:

> App is not defined

Would you guys show me how to subscribe to a channel in Rails 6? Many thanks!

**Comment by simukappu** [comment]
Hi,
This seems to be a issue of Action Cable configuration, not of a *activity_notification* gem. Please see [Action Cable description](https://guides.rubyonrails.org/action_cable_overview.html).

By the way, test application included in *activity_notification* currently [works with Rails 6 as default](https://github.com/simukappu/activity_notification/blob/master/Gemfile): See https://github.com/simukappu/activity_notification/tree/master/spec/rails_app
Demo application running on Heroku is also working with Rails 6: https://activity-notification-example.herokuapp.com
Thanks!

**Comment by truongnmt** [comment]
Thanks for your response!

Hmm I mean the action cable just not work. As I see on demo I'm expecting to see notification in realtime not refresh the page.

http://www.giphy.com/gifs/PmS37uLiI6us9ZPg8v

The problem is not Rails 6, just I dont know how to deal with the subscriptions to channel js code.

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.
