### ISSUE TITLE
different class/table name instead of 'notification'

### ISSUE THREAD

**Issue by bart3r** [simukappu/activity_notification#133]
We already have a Notification class and notifications table in the database.

We'd like to use this gem, but need to use different class/table names.
Is this possible?

**Comment by simukappu** [comment]
No, but partially yes.
*activity_notification* gem requires pre-defined notification model and database table. You can specify table name used by notification model in *activity_notification*. You can also read notification data from this table by your own model. So, what you need to do is:
1. Create new database table by *activity_notification* migration generator, or create your own table which has pre-defined columns for *activity_notification* table.
2. Migrate your notification data from existing table to created table.
3. Set *config.notification_table_name* to your table in *activity_notification* configuration.
4. Use *activity_notification* by *activity_notification* APIs

Does my answer make sense?

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.
