### ISSUE TITLE
Rails 6 Zeitwerk::NameError when deployed to heroku

### ISSUE THREAD

**Issue by Jonathanlau92** [simukappu/activity_notification#134]
Hi,

Thank you for the amazing gem. It really helps in my development of in-app notification feature, but i received an error while deploying to heroku, not sure if anyone has face the same problem. Been trying to figure out the error to no-avail. My app currently doesn't use the action_cable part of this gem.

` Unable to load application: Zeitwerk::NameError: expected file <APP_URL>/app/channels/activity_notification/notification_api_with_devise_channel.rb to define constant ActivityNotification::NotificationApiWithDeviseChannel, but didn't`

The above is taken from heroku logs.

Thank you in advance for your time.

**Comment by simukappu** [comment]
This *activity_notification* online demo is working on Heroku:
 https://github.com/simukappu/activity_notification#online-demo

All demo code is included in this repository and might be helpful to you.

**Comment by Jonathanlau92** [comment]
@simukappu oh, okay. Thanks for the reply. I'll try it.
