### ISSUE TITLE
filter targets when calling send_batch_unopened_notification_email

### ISSUE THREAD

**Issue by bart3r** [simukappu/activity_notification#136]
### Problem or use case
When you call send_batch_unopened_notification_email, you can't seem to use a where condition on the User record. This means that we can't send batch emails to users at different frequencies (daily, weekly, monthly). I've tried using the custom_filter option, but that only filters attributes in the notifiations table, not the target table.

### Expected solution
Provide a way to be able to filter on the target, so that batch emails can hit different groups of users.

If anyone has a workaround, let me know.

**Comment by simukappu** [comment]
How about following two steps?
1. Filtering target ids
2. Call *send_batch_unopened_notification_email* with *custom_filter* by filtered target ids

For example,
```ruby
target_ids = User.where(segment: "monthly").plunk(:id)
User.send_batch_unopened_notification_email(batch_key: 'batch.comment.post', filtered_by_key: 'comment.post', custom_filter: ["target_id IN ?", target_ids])
```
But it may have performance issue.

If you need to join notifications table on target table when *custom_filter* called, please give us feedback.
Thank you!

**Comment by simukappu** [comment]
Closing this issue for now. Please give us any other feedback if you have. Thanks!
