### ISSUE TITLE
Emails not getting sent even after adding send_later: false

### ISSUE THREAD

**Issue by shilpi230** [simukappu/activity_notification#144]
### Steps to reproduce
`notify = Model.last.notify "users", send_later: false` 

### Expected behavior
User should receive mail

### Actual behavior
Rails console says this that email has been delivered.

### System configuration
**activity_notification gem version**: 2.1.2
**Rails version**: 6.0.3.2
**ORM**: ActiveRecord

**Comment by simukappu** [comment]
It seems to be Action Mailer configuration issue since Rails console says that email has been delivered.
Can you send email from your Rails application by Action Mailer?

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.
