### ISSUE TITLE
Single Table Inheritance on target user

### ISSUE THREAD

**Issue by crustyratfink** [simukappu/activity_notification#16]
I'm having trouble with single table inheritance on my devise user (例えば, BuyerUser < User(devise) and SellerUser < User(devise). When I try to look at notifications for a BuyerUser, I get "Defferent type of current resource BuyerUser with devise resource SellerUser has been passed to SellerUser#authenticated_with_devise?. You have to override SellerUser#authenticated_with_devise? method or set devise_resource in acts_as_target."

What do you think? Is there a way to tell it to always use the superclass as the devise resource for both types of derived classes?

（ところで、違うのは「different」です。）

**Comment by crustyratfink** [comment]
Disregard. Got that part straightened out (side effect of bad seed data). But it turns out that this keeps coming up with target.to_resource_name, so I'm going to just write something specific to this situation. Thanks!

**Comment by simukappu** [comment]
Thank you for your comment! Actually, it is not expected to use `devise_resource` with single table inheritance, but this is for composite model (for example, `Admin` who belongs to `User`).

On the other hand, we can handle this to use `devise_resource` in `acts_as_target` and `becomes` method like this.

```
class BuyerUser < User
  acts_as_target email_allowed: false,
    devise_resource: ->(buyer_user) { buyer_user.becomes(User) }
end
```

This exception is simply intended to prevent missing `devise_resource` configuration. Currently, `current_resource` and `devise_resource` are compared by `instance_of?` method here,
https://github.com/simukappu/activity_notification/blob/master/lib/activity_notification/models/concerns/target.rb#L183
but I think this should return true for single table inheritance so I will update this to use `is_a?` method.

Also typo of "Defferent" will be fixed. Thank you!
