### ISSUE TITLE
Rails 7 support

### ISSUE THREAD

**Issue by tachyons** [simukappu/activity_notification#164]
### Steps to reproduce
try to add this gem in a rails 6 project

### Expected behavior
It works

### Actual behavior
bundle fails to resolve

**Comment by simukappu** [comment]
Thank you for creating this issue and your PR. We'd like to allow use with Rails 7.0, but the gem is not tested with Rails 7.
Can you add test gemfile to [gemfiles](https://github.com/simukappu/activity_notification/tree/master/gemfiles) directory and confirm if it works fine?

**Comment by simukappu** [comment]
I've allow use with Rails 7.0 in master branch.

The latest [devise_token_auth](https://rubygems.org/gems/devise_token_auth) does not support Rails 7.0 yet. The [pull request](https://github.com/lynndylanhurley/devise_token_auth/pull/1517) has been already merged into master branch.
Also the latest [mongoid](https://github.com/mongodb/mongoid) does not support with Rails 7.0 yet. The [feature request](https://jira.mongodb.org/browse/MONGOID-5193) was opened and the [commit](https://github.com/mongodb/mongoid/commit/483aa5a0377cf66ea0b25916c61fbf2af604d488) has been already merged into master branch.

**Comment by simukappu** [comment]
We've published as v2.2.3.
