### ISSUE TITLE
Batch functionality with optional targets

### ISSUE THREAD

**Issue by jbarbarosa** [simukappu/activity_notification#168]
Is it possible to use the batch functionality with targets besides e-mail?

Thanks in advance

**Comment by simukappu** [comment]
No, we don't have a prepared function. If you want to send batch notifications by optional targets, you can use [Target.send_batch_unopened_notification_email](https://github.com/simukappu/activity_notification/blob/master/lib/activity_notification/models/concerns/target.rb#L114-L143) implementation as a reference.
Closing this issue for now. Please reopen if required.
