### ISSUE TITLE
CanCanCan support

### ISSUE THREAD

**Issue by Dariusch** [simukappu/activity_notification#17]
Hey guys,
I was just trying to implement your gem into my legacy rails 4.2.8 app and came across an error with [cancancan](https://github.com/CanCanCommunity/cancancan).
Cancancan allows me to authorize every resource by setting a `check_authorization` in my ApplicationController. I am not using Devise, for the record.  
Cancancan throws me an error `This action failed the check_authorization because it does not authorize_resource. Add skip_authorization_check to bypass this check.`
After generating your controllers and adding the `skip_authorization_check` flag it still does not work.
Is there a chance we can fix this? Do you need a sample app to test the behaviour?

**Comment by simukappu** [comment]
Yes, if you provide a sample app and how to reproduce it, I will investigate and try to fix it.
Thanks!

**Comment by Dariusch** [comment]
I just created a sample app here:
https://github.com/Dariusch/cancan_activity_monitor_error
Hope this will help

**Comment by maxbize** [comment]
In case anyone stumbles over here and still needs an answer, you can use the conditional authorization checks defined here: https://github.com/ryanb/cancan/wiki/Ensure-Authorization
