### ISSUE TITLE
Deleting the Notifiable 

### ISSUE THREAD

**Issue by johncadengo** [simukappu/activity_notification#170]
I have a question. When a notifiable makes a notification, but then we delete the notifiable, how should we handle the original notification? 

For example, if we create a notification every time a chat gets a new message, and we assign the message as the notifiable. What do we do when that message is deleted?

Is it assumed that we will delete the notification if the notifiable is deleted? What if we want to keep the notification, but just gracefully handle the case where there is no notifiable?

Is there a way to gracefully load the notification partials so that they don't error trying to load up a notifiable that doesn't exist?

**Comment by simukappu** [comment]
You can use *dependent_notifications* option in *acts_as_notifiable* to delete notifications when the notifiable has been deleted. See this description for more details : https://github.com/simukappu/activity_notification/blob/master/lib/activity_notification/roles/acts_as_notifiable.rb#L179-L189
In this gem, notifications have no information if notifiable does not exists. You can ignore notifications with deleted notifiables in a view layer, but it seems to be rare use cases.

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.
