### ISSUE TITLE
Question about optional_targets

### ISSUE THREAD

**Issue by inferno** [simukappu/activity_notification#18]
Hi!

Is `optional_targets` works as intended? I tried implement custom SMS notifications. And i can't...

My steps:

1. created user model with `acts_as_target`
2. created other model `Heat` with

```ruby
  require 'custom_optional_target/sms'
  acts_as_notifiable :owners,
                     targets: User.first,
                     optional_targets: {
                       CustomOptionalTarget::Sms => {}
                     }
```
3. created `CustomOptionalTarget::Sms`, just dummy for example
```ruby
module CustomOptionalTarget
  class Sms < ActivityNotification::OptionalTarget::Base
    def initialize_target(options = {})
    end

    def notify(notification, options = {})
      puts 'bingo'
    end
  end
end
```
 
4. when i try notificate user about something from heat, `Heat.last.notify(:owners, key: 'heat.ready')`, `CustomOptionalTarget::Sms` never called. What i am doing wrong? Thanks.

**Comment by simukappu** [comment]
Hi,

`targets` option of `acts_as_notifiable` must be array. Please try as follows,

```ruby
require 'custom_optional_target/sms'
  acts_as_notifiable :owners,
                     targets: [User.first],
                     optional_targets: {
                       CustomOptionalTarget::Sms => {}
                     }
```

Thanks!

**Comment by inferno** [comment]
Yep, my fault. But still not working.

**Comment by inferno** [comment]
Normal notification sent, but addition to `CustomOptionalTarget::Sms` — no.

**Comment by simukappu** [comment]
OK, please try to use target model name for notification symbol as follows,

created other model Heat with

```
  require 'custom_optional_target/sms'
  acts_as_notifiable :users,
                     targets: [User.first],
                     optional_targets: {
                       CustomOptionalTarget::Sms => {}
                     }
```

Call `notify` as

```
Heat.last.notify(:users, key: 'heat.ready')
```

**Comment by simukappu** [comment]
If it works, I will try to fix this to use any notification targets name with optional_targets in the next version.

**Comment by inferno** [comment]
Damn, its work! I thought, that first params is just key for binding in notify method.

**Comment by simukappu** [comment]
Great.
Yes, it should be just key for binding in notify method. Thank you for your reporting!

**Comment by inferno** [comment]
Thank you, for fast and complete answer ;)

**Comment by simukappu** [comment]
I found it is difficult to use another name for binding since many internal modules call configured param in notifiable model by `acts_as_notifiable` with target model class name.
Therefore, please use the plural symbol name of your target model as the first param and key in `acts_as_notifiable`.

I have updated README and will close this issue.
Thank you for your reporting!
