### ISSUE TITLE
A way to access notifiable details in notifiable_path

### ISSUE THREAD

**Issue by bastianwegge** [simukappu/activity_notification#24]
Hey,

I was just wondering if there's a way to access the notifiable details in the notifiable_path. I'm doing something like this:

```
  acts_as_notifiable :users,
                     targets: ->(object, key) {
                       get_notifiable_user_array_for(object, key)
                     },
                     notifiable_path: :objects_notifiable_path
```

Now since my object is pretty complex and has about 8 different notification-keys I'm wondering if I can access the key to adjust the notifiable_path the user is sent to. I'm using a basic tabs-layout on the detail page of my object that accepts `/objects/5#documents` for example.

I know this is something I could ask on Stackoverflow but since it has to do with a complex usage-example of your library I was wondering if there's a solution that might improve the docs as well.

All the best!

**Comment by simukappu** [comment]
Hi bastianwegge,

You can use lambda function for *notifiable_path* option. The first argument of lambda function is *notifiable instance* and the second is *notification key*.
For example, you can specify *notifiable_path* for each key in your function like this,
```
acts_as_notifiable :users,
  targets: ->(object, key) {
    get_notifiable_user_array_for(object, key)
  },
  notifiable_path: ->(object, key) {
    case key
    when 'key1' then object.objects_notifiable_path_1
    when 'key2' then object.objects_notifiable_path_2
    else object.objects_notifiable_path
  }
```

If your notification keys are representing the name of detail page like `documents`, you can directly use it like this,
```
acts_as_notifiable :users,
  targets: ->(object, key) {
    get_notifiable_user_array_for(object, key)
  },
  notifiable_path: ->(object, key) { object.objects_notifiable_path + "##{key}" }
```
Please try it!
Thanks.

**Comment by bastianwegge** [comment]
Thanks again @simukappu! 

Might I suggest to add this to the documentation [here](https://github.com/simukappu/activity_notification#notifiable-as-an-activerecord-model)? If you want I can provide a PR for this.

**Comment by simukappu** [comment]
Hi,
Yes, appreciate it if you could provide a pull request!

**Comment by simukappu** [comment]
Thank you bastianwegge!
