### ISSUE TITLE
Is it supposed to work on Rails 5.1?

### ISSUE THREAD

**Issue by benjam1n** [simukappu/activity_notification#25]
Hi there!

Has anyone tested the gem with Rails 5.1? I mean, probably I'm doing something wrong.
It's a bit confusing when after "bin/rails generate activity_notification:install" it says I should have:

```
include ActivityNotification::Notifiable
acts_as_notifiable :users ...
```
```
include ActivityNotification::Target
acts_as_target email: :email, email_allowed: :confirmed_at
```

But in readme it doesn't say to include 'includes'. 

What's the right way?

Thanks,
Ben

**Comment by simukappu** [comment]
Hi,

Yes, *activity_notification* is tested with Rails 5.1 in our Travis CI.

When you use *ActiveRecord* ORM (as default), *activity_notification* automatically load *Notifiable* and *Target* modules to your models here,
https://github.com/simukappu/activity_notification/blob/master/lib/activity_notification/models.rb#L20
so you don't need include *Notifiable* or *Target* manually.
When you use other ORM like *Mongoid*, you have to include *Notifiable* or *Target* in your models manually.
I have updated README shown after installation to make it simple.

Thanks

**Comment by simukappu** [comment]
I will close this issue.
