### ISSUE TITLE
Mailer integration from initializer option missing

### ISSUE THREAD

**Issue by bastianwegge** [simukappu/activity_notification#30]
Hey @simukappu,

I just noticed that default Mailer option in `initializers/activity_notification.rb` [here in activity_notification.rb#L39](https://github.com/simukappu/activity_notification/blob/9b41f7874a7d204ba63f686256c832dfaf1dbf37/lib/generators/templates/activity_notification.rb#L39) is not really taken in concern.

Maybe I'm missing something.

All the best.

**Comment by simukappu** [comment]
Hi, @bastianwegge,

Oh, I found there is a bug that this configuration is currently ignored. I will fix this issue in this week.
You are not missing anything. Thank you for your report!

**Comment by simukappu** [comment]
I have fix it in the master branch. Could you try again from master branch?

**Comment by bastianwegge** [comment]
Seems to work for me but it would be easier to evaluate working code using tests, don't you think? ⛺️

**Comment by simukappu** [comment]
Yes, 100% agree. It is little difficult to write test for these configuration because it is automatically initialized when the gem is loaded.
I will try to write test code by injecting the configuration.
If you could provide pull request for this, I would appreciate it.

Thanks

**Comment by simukappu** [comment]
I have added a test and will close this issue.
