### ISSUE TITLE
Weird logs - Creating scope :filtered_by_type...

### ISSUE THREAD

**Issue by benjam1n** [simukappu/activity_notification#31]
Hi there!

I keep seeing this in my logs but can't figure out why:

```Creating scope :filtered_by_type. Overwriting existing method ActivityNotification::ORM::ActiveRecord::Notification.filtered_by_type.```

I'm not doing any kind of overwriting and there isn't anything like "filtered_by_type" in my code.

Thanks,
Ben

**Comment by simukappu** [comment]
Hi,

What did you do before you met this error? How did you configure your application and *activity_notification*? Could you please provide more information or small case of your application with this issue?

Thanks

**Comment by bastianwegge** [comment]
@benjam1n Can you provide an example-project?

**Comment by simukappu** [comment]
I will close this issue in a few days since information is not enough...
