### ISSUE TITLE
How do I use in gem external to rails project?

### ISSUE THREAD

**Issue by chao-mu** [simukappu/activity_notification#35]
I'm organizing my code such that the particular model I want to use activity_notification (User) lives in its own gem. This gem is then included by my rails application wherein I have such files as config/initializers/activity_notification.rb. Unfortunately this split does not appear to work, producing the error "uninitialized constant ActivityNotification::Target::Association" if I use acts_as_notification_target +  require "activity_notification" (without the require I get undefined local variable or method `acts_as_notification_target").

I have followed the instructions for setup and have the initializer defined in the rails project including this gem. My hunch is that it has to do with needing to run the config initializer before the gem load, which doesn't happen by default and I'm not sure how to make that go.

Thank you in advance.

**Comment by simukappu** [comment]
Hi,

Yes, you're right. You need to run the config initializer before the gem load. `ActivityNotification::Target::Association` will be loaded with your ORM configuration since this class is defined for each ORM.
```ruby:activity_notification.rb
  def self.configure
    yield(config) if block_given?
    autoload :Association, "activity_notification/orm/#{ActivityNotification.config.orm}"
  end
```
See https://github.com/simukappu/activity_notification/blob/master/lib/activity_notification.rb#L45

If you have any idea to solve your problem, please give me a feedback or send pull request!
Thanks.

**Comment by chao-mu** [comment]
Would it work if we did something like...

On my side I call `require "activity_notification/orm/active_record.rb"` (or `mongoid.rb`) and in active_record.rb there's a call like

```
ActivityNotification.configure do |config|
    config.orm = :active_record
end
```

Or you could have it default to active_record if unspecified and squash the most common case?

**Comment by chao-mu** [comment]
I do the following in my code and get farther
```
require 'activity_notification'

ActivityNotification.configure do |config|
    config.orm = :active_record
end
```

However this leads to `Gem Load Error is: uninitialized constant ActivityNotification::Mailer` which I can't seem to find.

**Comment by chao-mu** [comment]
Ah, I see the issue, there are other config values needed upon load

```
      # Defines mailer class to send notification
      def set_notification_mailer
        @@notification_mailer = ActivityNotification.config.mailer.constantize
      end
```

**Comment by chao-mu** [comment]
Okay, I have a work around using ActiveSupport.on_load(:after_initialize). In my gem I have a file in lib which requires the various classes that are exposed. I wrapped those all in aforementioned on_load. So far so good, though I haven't done heavy testing.
