### ISSUE TITLE
Can't create Notification in Rails 5 (likely due to belongs_to needing optional)

### ISSUE THREAD

**Issue by hhff** [simukappu/activity_notification#36]
With a boilerplate setup in Rails 5:

```
class User < ApplicationRecord
  acts_as_target email: :email
end
```

```
class Invite < ApplicationRecord
  acts_as_notifiable :users,
    targets: -> (invite, key) {
      [invite.receiver]
    }
end
```

```
@invite.notify :users
```

No notifications are being created.  Tracing the call through to the `create(notification_fields)` line, I can see that the validation message is:

```
{
   :group => [
        [0] "must exist"
    ],
    :notifier => [
        [0] "must exist"
    ]
}
```

My guess is that we need extra optional `belongs_to` params, like this one:
https://github.com/simukappu/activity_notification/blob/master/lib/activity_notification/orm/active_record/notification.rb#L35

Is this correct, or am I missing something?  I don't need grouping for this feature, and I don't understand the notifier field.

**Comment by simukappu** [comment]
There was missing a test case. I've merged your pull request. Thank you!
