### ISSUE TITLE
Notifier ID

### ISSUE THREAD

**Issue by AkshayGoradia** [simukappu/activity_notification#38]
Hey there,

I've got pretty much everything up and running, however when I create a new Notification record, it doesn't include a notifier_id. I added 'acts_as_notifier' to my User model – is there anything else I must do?

Thanks!

**Comment by simukappu** [comment]
Hi,

You have to specify `notifier` option in calling `notify` API, not only `acts_as_notifier` in *Notifiable* model, like this;
```
@comment.notify :users, key: 'custom.comment', notifier: @comment.user
```
Try this and feedback if you have any trouble. Thanks!

**Comment by AkshayGoradia** [comment]
Perfect, thanks so much!
