### ISSUE TITLE
Unpermitted parameters

### ISSUE THREAD

**Issue by dachinat** [simukappu/activity_notification#39]
Hello. I'm having rails 5.1.3 and ruby 2.4.1p111. I am getting 
> Unpermitted parameters: :subdomain, :target_type, :devise_type, :user_id

in console output for `@my_instance.notify :users`. I have executed this code in rails console and it rolls-back. Would you kindly please offer a solution this?

**Comment by dachinat** [comment]
I had to add `group` and `notifier` to models.

**Comment by dachinat** [comment]
I have added added github repo reference to Gemfile.

**Comment by rikkipitt** [comment]
@dachinat, I appreciate this was a long time ago, but did you manage to get past this issue?
