### ISSUE TITLE
Subscriptions for specific notifiable?

### ISSUE THREAD

**Issue by chao-mu** [simukappu/activity_notification#40]
Using the documentation example of articles/comments, is there a way to subscribe the user to the comments of a specific article baked into activity_notification? As far as I can tell, subscriptions are key based and I could accomplish this by embedding the article's ID in the notification's key.  Is there a better way? Would this be bad practice?

Thank you!

**Comment by chao-mu** [comment]
My alternative was to create a table like so

    create_table :notifiable_subscriptions do |t|
      t.integer :user_id, unsigned: true, foreign_key: true, null: false
      t.belongs_to :notifiable, polymorphic: true
      t.timestamps
    end

and manage it myself, but that then takes some of the "magic" out of the gem.

**Comment by chao-mu** [comment]
If this were to be added to core activity_notifications, I imagine the subscriptions table including a nullable notifiable relationship that when defined restricts to notifications matching both key and notifiable.

**Comment by simukappu** [comment]
Hi,

You can do this by using the notification key including *article's id* like,
```
@comment.notify(:users, group: @comment.article, key: "comment.created.#{@comment.article.id}")
```
Subscription management in this gem works for each article.
A problem of this solution is that notification view management for each key will be difficult. So you should override notification key and make the gem find common template for all comment notifications like this,
```
class Comment < ActiveRecord::Base
  acts_as_notifiable :users,
    targets: ->(comment, key) {
      # We need more simple API. It is also OK to send notification to User.all regardless of performance.
      User.where(id: Subscription.filtered_by_key(key).where(target_type: 'User', subscribing: true).pluck(:id)) - [comment.author]
    },

...

  def overriding_notification_template_key(target, key)
    key.include?("comment.created.") ? "comment.created" : key
  end

  def overriding_notification_email_key(target, key)
    key.include?("comment.created.") ? "comment.created" : key
  end
end
```

Thanks!

**Comment by chao-mu** [comment]
Thank you for the response! It jump started my brain.

In my actual code, there are 1. multiple models can be commented on (the comment model has a polymorphic relationship with a "commentable") and 2. users can "watch" a model, subscribing them to comments and other changes to that model. Here is what I came up with:

I have a Concern for models that a user may want to watch for changes on

  module WatchableModelBehavior
    extend ActiveSupport::Concern

    included do
      def watch_key
        [self.model_name.singular, self.id].join(".")
      end

      def watch_subscription(user)
        user.find_or_create_subscription(self.watch_key)
      end

      def watch(user)
        self.watch_subscription(user).subscribe
      end

      def unwatch(user)
        self.watch_subscription(user).unsubscribe
      end

      def watchers
        subs = ActivityNotification::Subscription.filtered_by_key(self.watch_key)
          .where(target_type: 'User', subscribing: true)
        User.where(id: subs.pluck(:id))
      end
    end
  end

And my comments class that references the "watchers" function defined previously

  class Comment < ApplicationRecord
    belongs_to :commentable, polymorphic: true
    belongs_to :author, class_name: "User"

    acts_as_notifiable :users,
      targets: ->(comment, key) {
        comment.commentable.watchers - [comment.author]
      },
      notifiable_path: :thread_url

    def thread_url
      self.commentable.thread_url
    end
  end

And a Concern for models that I want to support comments

  module CommentableModelBehavior
    extend ActiveSupport::Concern

    included do
      has_many :comments, as: :commentable

      def comment!(c)
        self.comments << c
        c.commentable.watch(c.author)
        c.notify :users, key: "comment.new", notifier: c.author
      end
    end
  end

And to get a model watchable and commentable:

    include WatchableModelBehavior
    include CommentableModelBehavior

Does this make sense or ass it bass ackwards?

**Comment by chao-mu** [comment]
I would then look for a way to retrieve all notifications related to a given model, even for users who have not explicitly subscribed to it. Would that even be possible?

**Comment by chao-mu** [comment]
I currently plan to accomplish this by making the watched model a target and including it in the "watchers" function.

**Comment by simukappu** [comment]
Hi,

If you just want to send notifications to watchers, you will handle this by target definition only.

* *article* has many *comments*
* *comment* belongs to *article*
* *article* has many *bookmarks*
* *bookmark* belongs to *article* and *user*

Then,
```
class Article < ActiveRecord::Base
  has_many :comments
  has_many :watchers, through: bookmarks, source: :user
end

class Comment < ActiveRecord::Base
  belongs_to : article
  acts_as_notifiable :users,
    targets: ->(comment, key) {
      comment.article.watchers - [comment.author]
    }
end
```

That's it. This is just Ruby on Rails matter, not *activity_notification*. What do you think?

**Comment by chao-mu** [comment]
This worked for me well. Thank you!
