### ISSUE TITLE
Slack Notification Channel Using Symbol

### ISSUE THREAD

**Issue by AkshayGoradia** [simukappu/activity_notification#43]
My optional slack target is as follows, where '@user' is a member of the slack channel:

`ActivityNotification::OptionalTarget::Slack  => {
          webhook_url: 'https://hooks.slack.com/services/XXXXXX',
          target_username: :slack_username, channel: @user, username: 'system', icon_emoji: ":ghost:"
        }`

The above works perfectly. But since I want to change the channel the message is sent to depending on the notified user, I was hoping to change the code to the below, where ':slack_username' is a User's username on slack (including the '@' sign).

`ActivityNotification::OptionalTarget::Slack  => {
          webhook_url: 'https://hooks.slack.com/services/XXXXXX',
          target_username: :slack_username, channel: :slack_username, username: 'system', icon_emoji: ":ghost:"
        }`

For some reason, this does not work (comes up with a slack channel cannot be found error). Does the 'channel' parameter not accept symbols?

Thanks!

**Comment by simukappu** [comment]
Hi,

Currently, *channel* parameter in `ActivityNotification::OptionalTarget::Slack` does NOT accept symbols.
*target_username* parameter is passed through *notification.target.resolve_value* method to convert params from notification field as follows.
https://github.com/simukappu/activity_notification/blob/master/lib/activity_notification/optional_targets/slack.rb#L28
However, *channel* parameter is directly passed in * initialize_target* method as follows.
https://github.com/simukappu/activity_notification/blob/master/lib/activity_notification/optional_targets/slack.rb#L14

You can build your own custom optional target extending `ActivityNotification::OptionalTarget::Slack`. In other option, you can contribute this gem to send pull-request for updated code or your new optional target implementation.

Thanks!

**Comment by AkshayGoradia** [comment]
Thanks for your reply! I made these changes to my forked version to test:

def initialize_target(options = {})
        @target_username = options.delete(:target_username)
        **@channel = options.delete(:channel)**
        @notifier = ::Slack::Notifier.new(options.delete(:webhook_url), options)
 end

def notify(notification, options = {})
        target_username = notification.target.resolve_value(options.delete(:target_username) || @target_username)
        **channel = notification.target.resolve_value(options.delete(:channel) || @channel)**
        @notifier.ping(render_notification_message(notification, options.merge(assignment: { target_username: target_username**, channel: channel** })))
end

I don't get any errors this time, but now all of my notifications go to the "general" slack channel instead of the symbol value I have for channel (ex. '@bob'). Did I do something incorrect?

**Comment by bob** [comment]
Hello

**Comment by simukappu** [comment]
This seems to be the issue of *slack-notifier* and slack API. Please check API reference and your Webhook configuration.
https://github.com/stevenosloan/slack-notifier
https://api.slack.com/docs/message-formatting

Thanks
