### ISSUE TITLE
NameError: uninitialized constant ActivityNotification::Target::Association

### ISSUE THREAD

**Issue by nkhdo** [simukappu/activity_notification#52]
Hi,

I'm getting this error after installing the gem, and running the DB migration:
`NameError: uninitialized constant ActivityNotification::Target::Association`
Please help!

Rails version: 5.1
Gem version: 1.4.4
Using ActiveRecord

Thanks and Regards,

**Comment by PavelTkachenko** [comment]
You probably forgot about initializers or trying to do this after declaring `acts_as_target` in your models. Remove all `acts_as_target` from models and run `rails generate activity_notification:install`. Then try again.

**Comment by simukappu** [comment]
Thanks @PavelTkachenko!
Is there still any problem? I will close this issue.
