### ISSUE TITLE
Conditional Email Sender based on notification details

### ISSUE THREAD

**Issue by bastianwegge** [simukappu/activity_notification#53]
Hey @simukappu and belated happy new year,

simple question down our path right now: Is it possible to change the email-sender based on notification details? We have several audiences on our platform and I'd like to address users from "noreply@ourdomain.com" and other user types from "support@ourdomain.com".

All the best!

**Comment by bastianwegge** [comment]
The following works but would make sense to add a small description to the readme:

```
config.mailer_sender = ->(key){ key === 'my.key' ? 'support@ourdomain.com' : 'noreply@ourdomain.com' }
```

**Comment by simukappu** [comment]
Hi @bastianwegge and happy new year,

We have no simple configuration to make multiple sender. It would be helpful if you could add above solution to our Readme. Thank you!

**Comment by bastianwegge** [comment]
Done! https://github.com/simukappu/activity_notification/pull/54
