### ISSUE TITLE
Error while running migration

### ISSUE THREAD

**Issue by andreierdoss** [simukappu/activity_notification#55]
Hello,

Great job with this gem. I'm really excited about using it. I am currently trying it out on Rails 5.2 and I'm getting this error: 

```
Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateActivityNotificationTables < ActiveRecord::Migration[4.2]
/Users/andrei/.rvm/gems/ruby-2.5.0@app/gems/activerecord-5.2.0.beta2/lib/active_record/migration.rb:527:in `inherited'
```

**Comment by simukappu** [comment]
Hi @andreierdoss,

Thank you for your reporting. `activity_notification` gem have not been tested with Rails 5.2 beta yet. It is tested with Rails 4.2, 5.0 and 5.1 with Travis CI.
If you could test it with Rails 5.2 beta and send pull request to development branch, I would appreciate it. After Rails 5.2 is published (not beta), we will test and support Rails 5.2 officially. Thanks!

**Comment by simukappu** [comment]
Merge to Rails 5.2 issue and I will close issue.
