### ISSUE TITLE
Paginating notifications

### ISSUE THREAD

**Issue by markedmondson** [simukappu/activity_notification#58]
I see there's a way to limit the returned count of notifications but no way to set an offset, I'm guessing this is partly due to the indexed caching in the count methods, is there any simple way you can see pagination being achieved (that isn't just paginating the potentially huge array of notifications)?

**Comment by adamcooper** [comment]
👍 

I would also like to have the ability to paginate the notifications.

**Comment by irondnb** [comment]
It can be achieved by making notifications ActiveRecord::Relation (e.g. fetching notifications again by id) and then paginate using just sql.
I'm using Kaminari in my projects, and it has method that wraps array to make it paginable.

`@notifications = @target.notifications.order(created_at: :desc)
paginate_array = Kaminari.paginate_array(@notifications)
@notifications = paginate_array.page(params[:page]).per(params[:per_page])`

It would be great though if notifications could be ar relation by default.

**Comment by simukappu** [comment]
We've added *later_than* and *earlier_than* filter options to notification index API at [v2.1.0](https://github.com/simukappu/activity_notification/blob/master/CHANGELOG.md). See also #108.
We can paginate notifications index using these filter options.

If you have any more requirements about pagination, please give us a specific feedback. Thanks!

**Comment by markedmondson** [comment]
I'm not sure I see how using the date lets you paginate, you'd need to know the before/after dates beforehand in order to determine the next set of dates to keep the page size the same. Maybe I'm missing something..?

**Comment by simukappu** [comment]
We can use *earlier_than* option to specify start point of the page, and use *limit* option to specify the page size. I don’t think this is a complete solution, so appreciate your feedback. What do you think?

**Comment by markedmondson** [comment]
Oh, I guess that could work... Effectively passing the date from the last item in the query for the next page request. I'll give it a go - thanks :)

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.
