### ISSUE TITLE
Custom controller

### ISSUE THREAD

**Issue by 8vius** [simukappu/activity_notification#60]
Need some guidance here, I created my custom controller `users/notifications_controller` and set the notify accordingly in the routes, as per the instructions on the README, and even though the notifications do seem routed to it doing a binding.pry in there doesn't work, seems like it's hitting the default controller anyway, how can I route it to my controller?

**Comment by simukappu** [comment]
Write your error logs here.

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required with your *route.rb* and the result of `rake routes`.
