### ISSUE TITLE
Rails 5.2 - Only one email notification gets sent

### ISSUE THREAD

**Issue by rgbskills** [simukappu/activity_notification#61]
Only one notification email gets sent, then if I restart the server I can send another one. 

I have no idea how to fix this :(

Here is video demonstrating the issue.
http://somup.com/cFe026Vgmd
I start by restarting docker and I send a Notification.. It works the first time
Then I restart docker and it works again only the first time

user.rb (Model)
```
acts_as_target email: :email, email_allowed: :created_at
```
comment.rb (Model)
```
acts_as_notifiable :users,
    targets: ->(comment, key) {
      ([comment.commentable.user] + comment.commentable.commented_users.to_a - [comment.user]).uniq
    },
    tracked: true,
    email_allowed: true,
    notifiable_path: :commentable_notifiable_path
```

I tested this locally and on staging and its the same behaviour :(

**Comment by simukappu** [comment]
Currently, the gem does not pass the tests with Rails 5.2. Work in progress.
If you can contribute this upgrade, I would appreciate it. Thanks!

**Comment by simukappu** [comment]
https://github.com/simukappu/activity_notification/issues/71
