### ISSUE TITLE
Receiving ActiveRecord::RecordNotFound in ActivityNotification::NotificationsWithDeviseController#index

### ISSUE THREAD

**Issue by RailsCod3rFuture** [simukappu/activity_notification#62]
When I use the link_to method <%= link_to 'Notifications, user_notifications_path(current_user) %> I receive **Couldn't find User**.  I'm using friendly_id for usernames. I believe the username is what activity_notification is unable to recognize. **http://127.0.0.1:3000/users/dantheman/notifications**

**Comment by RailsCod3rFuture** [comment]
How do you get the gem to function properly when I'm using the username attribute instead of the id?

**Comment by RailsCod3rFuture** [comment]
Using current_user.id works. My second issue is how the address looks. Can I hide the url for the users/3/notifications to only show /notifications?

**Comment by truongnmt** [comment]
@RailsCod3rFuture but on open notification item it still can't find resources, for example resource is user.

**Comment by RailsCod3rFuture** [comment]
I forgot to mention that I was using friendly_id gem. I don't know if this gem is compatible with that one. Besides the point, I think the notification link itself, that identifies the resource - Should be hidden by default. **/notifications** is much safer than **users/username/notifications** -- If anyone is up for the task of doing the plumbing to make the necessary changes. That would be nice.

**Comment by truongnmt** [comment]
I think you should open one at friendly_id repo

**Comment by simukappu** [comment]
We should handle this with #64.
