### ISSUE TITLE
ActivityNotification with commontator

### ISSUE THREAD

**Issue by pailoro** [simukappu/activity_notification#69]
I'm trying to use the ActivityNotification gem with the commontator. My model with comments is Post.rb. I generate the model of commontator and then put the code below, but I'm not receiving any notification. Is that correct? It is like the documentation.

```
module Commontator
  class Comment < ActiveRecord::Base

# acts_as_notifiable configures your model as ActivityNotification::Notifiable
  # with parameters as value or custom methods defined in your model as lambda or symbol.
  # The first argument is the plural symbol name of your target model.
  acts_as_notifiable :users,
  # Notification targets as :targets is a necessary option
  # Set to notify to author and users commented to the article, except comment owner self
  targets: ->(follow, key) {
    ([follow.user] + follow.user.to_a - [follow.user]).uniq
  },
  # Path to move when the notification is opened by the target user
  # This is an optional configuration since activity_notification uses polymorphic_path as default
```

**Comment by simukappu** [comment]
Sorry for my late response.
I think your target configuration is wrong. Your configuration
```
([follow.user] + follow.user.to_a - [follow.user]).uniq
```
will be always blank array because this means `[follow.user] - [follow.user]`.
Target configuration in README is just an example. I think your correct configuration is just
```
targets: ->(follow, key) { [follow.user] },
```
Please try again and let us know the result!

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.
