### ISSUE TITLE
403 Forbidden: Unauthenticated

### ISSUE THREAD

**Issue by dcalixto** [simukappu/activity_notification#70]
someone with the same issue configuring with devise?

after added notify_to :users, with_devise: :users in the routes?

```
Started GET "/users/bopa/notifications" for 127.0.0.1 at 2018-04-10 17:57:28 -0300
Processing by ActivityNotification::NotificationsWithDeviseController#index as HTML
  Parameters: {"target_type"=>"users", "devise_type"=>"users", "user_id"=>"bopa"}
  Rendering text template
  Rendered text template (0.1ms)
Filter chain halted as :authenticate_devise_resource! rendered or redirected
Completed 403 Forbidden in 6ms (Views: 4.4ms)
```

**Comment by cdesch** [comment]
What does your routes file look like?

**Comment by simukappu** [comment]
Maybe you are accessing the notifications page as unauthorized user with Device authentication. This is a correct response as `activity_notification` with Device authentication.
Closing this issue for now. Please reopen if required.
