### ISSUE TITLE
Support Rails 5.2

### ISSUE THREAD

**Issue by simukappu** [simukappu/activity_notification#71]
Currently, the gem does not pass the tests with Rails 5.2. Work in progress.

**Comment by simukappu** [comment]
https://github.com/simukappu/activity_notification/issues/55
https://github.com/simukappu/activity_notification/issues/71

**Comment by narutoo9x** [comment]
Basically, I add version to migration files, then rerun migrates, everything work ok.

**Comment by dgblanksaac** [comment]
Upgrading to Rails 5.2 then running 'bundle install' works flawlessly without the activity_notification gem. As soon as I add it back, both 'bundle install' and 'bundle update' spit out numerous errors. What am I missing?

**Comment by rgbskills** [comment]
Any updates on this issue?

**Comment by dgblanksaac** [comment]
I have not worked on it in a while. Still looking for a solution

**Comment by simukappu** [comment]
Let’s pass all the tests first.
Create *gemfiles/Gemfile.rails-5.2* and run as follows,
```
BUNDLE_GEMFILE=gemfiles/Gemfile.rails-5.2 bundle exec rspec
```
I have not been taking a time to fix it... I would appreciate it if you could contribute this.

**Comment by simukappu** [comment]
I have made the tests run with Rails 5.2 and release as new version 1.5.0
https://rubygems.org/gems/activity_notification/versions/1.5.0

**Comment by simukappu** [comment]
If you still have any other problem, please report us by publishing issues or send us pull requests to fix them.
Thanks!
