### ISSUE TITLE
Bullet doesn't support mongoid > 7.0.0

### ISSUE THREAD

**Issue by brenoperucchi** [simukappu/activity_notification#72]
I try to test dummy application and get the error

> Bundler::GemRequireError: There was an error while trying to load the gem 'bullet'.
> Gem Load Error is: Bullet does not support mongoid 7.0.0 yet

Maybe you lock the mongoid in gemspec 
`s.add_development_dependency 'mongoid', '>= 4.0.0', '< 7.0.0'`

**Comment by simukappu** [comment]
@brenoperucchi Thank you for reporting! I have fix it as you proposed.
