### ISSUE TITLE
Problem for STI tables.

### ISSUE THREAD

**Issue by DSKonstantin** [simukappu/activity_notification#75]
Hi all. 

I use STI solution for Users, Coach < Users. 

`
  acts_as_notifiable :users,
                     targets: -> (follow, key) { ([follow.followable]).uniq },
                     notifier: :follower,
                     optional_targets:  {
                         CustomOptionalTarget::AirshipSns => { }
                     }, tracked: true`

So, how I can use multiple `target_type`?

For example:

`  acts_as_notifiable %i[users, coaches],
                     targets: -> (follow, key) { ([follow.followable]).uniq },
                     notifier: :follower,
                     optional_targets:  {
                         CustomOptionalTarget::AirshipSns => { }
                     }, tracked: true`

> acts_as_notifiable %i[users, coaches]

Because 
`optional_targets:  {
                         CustomOptionalTarget::AirshipSns => { }
                     }`
don't work if `target_type` = :users but I have target = :coaches.

Thanks to all.

**Comment by simukappu** [comment]
Hi @DSKonstantin,

You should just write multiple`acts_as_notifiable` sections.
Please see https://github.com/simukappu/activity_notification/blob/master/spec/rails_app/app/models/comment.rb as an example.

**Comment by DSKonstantin** [comment]
@simukappu thank you for your feedback 👍

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.

**Comment by simukappu** [comment]
Reference #89
