### ISSUE TITLE
Option email_allowed is not being considered in configuration options

### ISSUE THREAD

**Issue by fedxgibson** [simukappu/activity_notification#79]
Hi! 
Apparently, setting email_allowed: false does not work. I ran into the code and I do not see any reference to this variable value being set anywhere.

I started looking into `lib/activity_notification/apis/notification_api.rb:339`. 

Any thoughts?

**Comment by simukappu** [comment]
Hi @fedxgibson,

`target.notification_email_allowed?` is called in `lib/activity_notification/apis/notification_api.rb#send_notification_email`.
https://github.com/simukappu/activity_notification/blob/master/lib/activity_notification/apis/notification_api.rb#L340
And `notification_email_allowed?` checks called target's `email_allowed:` field.
https://github.com/simukappu/activity_notification/blob/master/lib/activity_notification/models/concerns/target.rb#L156

Do you have any problem?

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.

**Comment by nicoalonsop** [comment]
Too late but I have the same problem. I avoided sending emails using `comment.notify :users, send_email: false`

My code is like this:
```
acts_as_notifiable :users,
    targets: ->(comment, key) {
      ([comment.article.user] + comment.article.commented_users.to_a - [comment.user]).uniq
    },
    # Not allow notification email, doesn't work
    email_allowed: false
```
