### ISSUE TITLE
Getting PG::AmbiguousColumn - column reference "group_owner_id" is ambiguous

### ISSUE THREAD

**Issue by vdruon** [simukappu/activity_notification#85]
Hi there ! 

I just started implementing activity_notification, with my User model as a target, and a Document model as the notifiable (with grouping enabled)

Here is the declaration in my Document model : 
`acts_as_notifiable :users, 
                      targets: -> (document, key) { document.community.users },
                      group: :community,
                      group_expiry_delay: 1.day,
                      parameters: -> (document, key) { {title: document.name} },
                      notifiable_path: :document_notifiable_path,
                      tracked: { only: [:create], key: 'community.document.create' },
                      dependent_notifications: :destroy`

The problem is when I try to retrieve a notification, and run notification#text, I get this error : 
`ActiveRecord::StatementInvalid: PG::AmbiguousColumn: ERROR:  column reference "group_owner_id" is ambiguous
LINE 1: ..._id) AS count_distinct_notifications_notifier_id, group_owne...
                                                             ^
: SELECT COUNT(distinct notifications.notifier_id) AS count_distinct_notifications_notifier_id, group_owner_id AS group_owner_id, notifier_type AS notifier_type FROM "notifications" LEFT OUTER JOIN "notifications" "group_owners_notifications" ON "group_owners_notifications"."id" = "notifications"."group_owner_id" WHERE "notifications"."target_id" = $1 AND "notifications"."target_type" = $2 AND "notifications"."group_owner_id" = 3 AND (group_owners_notifications.notifier_type = notifications.notifier_type) AND (NOT (group_owners_notifications.notifier_id = notifications.notifier_id)) GROUP BY "notifications"."group_owner_id", "notifications"."notifier_type"`

Could you please help me ?

**Comment by simukappu** [comment]
Hi @vdruon,

Thank you for your feedback!
What did your code do when this error was thrown? We would appreciate it if you could give us reprodusable code example.
In addition, where is this error thrown? Please give us stack trace we can find error origin in this gem.

Thanks!

**Comment by vdruon** [comment]
Hi there ! Thanks for your reply.

I just configured and setup the gem with 1 target (User) and 1 Notifiable (Document) and tried to run user.notifications.first.text just to see what happens and check return values.

That's when this exception happens. 
After checking, it comes from `ActivityNotification::ORM::ActiveRecord::Notification#unopened_group_member_notifier_count`
and
`ActivityNotification::ORM::ActiveRecord::Notification#unopened_group_member_notifier_count`
in their GROUP BY clause

**Comment by simukappu** [comment]
This `ActivityNotification::ORM::ActiveRecord::Notification#unopened_group_member_notifier_count` and `ActivityNotification::ORM::ActiveRecord::Notification#opened_group_member_notifier_count` methods are tested with PostgreSQL in travis CI here: 
https://github.com/simukappu/activity_notification/blob/master/spec/concerns/apis/notification_api_spec.rb#L1284-L1289
https://github.com/simukappu/activity_notification/blob/master/spec/concerns/apis/notification_api_spec.rb#L1291-L1296
and here as `NotificationApi#group_member_notifier_count`
https://github.com/simukappu/activity_notification/blob/master/spec/concerns/apis/notification_api_spec.rb#L923-L1173

Perhaps these test case is not enough. Can you create simple stand-alone code which we can reproduce this error?

Thanks!

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.
