### ISSUE TITLE
Unsubscribing specific notifiables

### ISSUE THREAD

**Issue by TheNeikos** [simukappu/activity_notification#86]
Hello :wave: and thank you for the great library!

I am currently adding `acticity_notification` to my app, where an `Artwork` `has_many` `Comment`s.
Now, if a `User` comments, the owner of the `Artwork` gets a notification. I would like them to be able to disable this notification for a specific artwork.

Similarly, one can reply to `Comment`s, the author of the parent comment also gets a notification. Here I would like them to also be able to disable this for a specific `Comment`/`Artwork`.

Is this possible with this gem? As a subscription seems to be for a given key rather than a Notifier

**Comment by simukappu** [comment]
Yes you can. You can use *targets* option in notifiable class.

```ruby
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user

  acts_as_notifiable :users,
    targets: ->(comment, key) {
      targets = ([comment.article.user] + comment.article.commented_users.to_a - [comment.user])
      targets = targets - [comment.article.user] if <comment is a specific Comment/Artwork>
      targets.uniq
    }
end
```

This *targets* option can be configured with any lambda function. See also [Readme's section](https://github.com/simukappu/activity_notification#configuring-target-models).

**Comment by TheNeikos** [comment]
While this would work, it feels wrong that the notifiable decides who actually receives it. Is there a way to filter it as a target? 

I am think about something like a filter on the User model that checks if they want to be notified of this. This way you can for example ignore everything where the notifier is an ignored user. 

From what I read in the docs this is not supported at the moment.

**Comment by markedmondson** [comment]
I too feel like this is an impending problem for our usage. It'd be nice to have a agreed pattern for unsubscribing to specific notifiables.

**Comment by simukappu** [comment]
Why don't you use separate notification keys and subscription for each? I would appreciate give us use cases and concrete enhancement request for it.
Thanks!

**Comment by markedmondson** [comment]
Our use case is a Slack sort of thing. So a user may wish to subscribe/unsubscribe to all notifications but they will also want to maintain channel specific subscriptions.

**Comment by simukappu** [comment]
Thanks! But I would like to ask you a question again.
Why don't you use separate notification keys for each slack channel as optional target? The users can subscribe/unsubscribe for each notification keys.

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.
