### ISSUE TITLE
Bulk insert for notify_all

### ISSUE THREAD

**Issue by svarione** [simukappu/activity_notification#87]
Hi,
First off, thank you for your great and useful work! I integrated your gem into a big project, but I came across some performance issues. In particular, the problem was on notify_all method.
To solve it, I changed some logic to integrate the bulk_insert gem. You can find my work at https://github.com/svarione/activity_notification/tree/bulk_insert. What do you think about it?

**Comment by simukappu** [comment]
Interesting. For now, only we can do to improve performance is to use background job tools such as *delayed_job* with *activity_notification* like this:
```
notifiable.delay.notify :users
```
I will try to take them in. Thank you for your suggestion!

**Comment by simukappu** [comment]
We will support asynchronous notification API natively to improve application performance instead of this bulk insert. Please see issue #29.

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.
