### ISSUE TITLE
STI and group_owners_only

### ISSUE THREAD

**Issue by svarione** [simukappu/activity_notification#89]
Hello, I's me again ;)! I found a small problem when I use Single Table Inheritance as a group. I solve it by changing the #to_class_name method to self.class.base_class.to_s.

Best regards

**Comment by simukappu** [comment]
Hi, thank you for your feedback :)
Can you point your changing? And, it would be helpful if you create pull request!

**Comment by simukappu** [comment]
Hi @svarione, can you provide the detail of you update commit? Perhaps your commit will help other users. Thanks!

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.

**Comment by apuntovanini** [comment]
I found same issues as @svarione for STI tables. I guess he meant https://github.com/simukappu/activity_notification/blob/5fcaf048eb5efd2f3cd32d801db53537c8a14e15/lib/activity_notification/common.rb#L102 this line
Also channels are broken for STI notifiers (or targets, or groups), possibly for the same reason

**Comment by simukappu** [comment]
Reopened to support STI models.

**Comment by simukappu** [comment]
We've just published as v2.1.4.
https://rubygems.org/gems/activity_notification/versions/2.1.4

Thank you!
