### ISSUE TITLE
How to change the Subject of the email message

### ISSUE THREAD

**Issue by daxterstroll** [simukappu/activity_notification#93]
Where can I change the subject line??
![default](https://user-images.githubusercontent.com/38354831/48665738-8b806980-eabc-11e8-84aa-d72ac120aed0.PNG)

**Comment by simukappu** [comment]
Hi, we have just updated [README.md](https://github.com/simukappu/activity_notification/blob/master/README.md) to describe how to customize email subject. See [Email subject](https://github.com/simukappu/activity_notification/blob/master/README.md#email-subject) and give us feedback if you have any issues. Thanks!

**Comment by daxterstroll** [comment]
Thank you very much, you helped me a lot! Your gem is great!
