### ISSUE TITLE
NoMethodError: undefined method `notify_to' for nil:NilClass

### ISSUE THREAD

**Issue by forsaken1** [simukappu/activity_notification#97]
Hello!

I have small problem with method `notify`

I call it: `@question.notify :users, key: 'user_question.vote', notifier: current_user` and I guarantee `@question` and `current_user` are not nil, but sometimes I get undefined method error.

Version: 1.5.1

Thanks!

**Comment by simukappu** [comment]
Please share the full log including *undefined method `notify_to' for nil:NilClass*.

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.
