### ISSUE TITLE
Routes with scope module don't work

### ISSUE THREAD

**Issue by nicoalonsop** [simukappu/activity_notification#98]
Hi,

I'm having problems to setup the gem. I'm getting `uninitialized constant AdministratorDashboard::ActivityNotification` when i go to http://localhost:3000/admin/notifications 

My configuration is:
```
# config/routes.rb
scope :admin, module: :administrator_dashboard, path: :admin, as: :admin do
    notify_to :administrators, with_devise: :users, devise_default_routes: true, routing_scope: :admin
end
```

Then i remove `module: :administrator_dashboard` and all works but i need to keep it.

Any suggestion?

Thanks in advance.

**Comment by Looooong** [comment]
You can move the scope to a separate block. In my project, I do something like this:

```ruby
  scope :admin, as: :admin do
    notify_to :staffs, routing_scope: :admin, with_subscription: true, with_devise: :staffs, devise_default_routes: true
  end

  # Same as scope :admin, module: :admin, path: :admin, as: :admin
  namespace :admin do
    # ...
  end
```

**Comment by simukappu** [comment]
I think the solution above works fine. Closing this issue for now. Please reopen if required.
